# Generated by Django 4.2.7 on 2023-11-14 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_category_contact_picture_contact_show_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="O número de telefone deve ser no formato: 'DD 12345-6789'.", regex='^\\d{2} \\d{5}-\\d{4}$')]),
        ),
    ]
